_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 64
context_length:
    value: 256
cosine_iters:
    value: 10000
max_lr:
    value: 0.001
min_lr:
    value: 0.0001
warmup_iters:
    value: 500
